fetchai/fetchd

app/app.go, go.mod, go.sum, x/wasm/internal/keeper/staking_test.go, x/wasm/internal/keeper/test_common.go, x/wasm/module.go
- Update to consensus v0.6.0 and sdk v0.7.0
- Add consensus staking begin blocker to app
=> Update consensus and sdk versions

cmd/wasmcli/main.go, cmd/wasmcli/txfmt.go
Add simple TX format server to `wasmcli` that can be used for automated transaction encodes
=> TX Format Server

docs/docs/cli-staking.md, docs/docs/delegator-guide-cli.md, docs/mkdocs.yml
Add documentation for querying validators stakes, delegations, and redelegations, as well as querying for users' rewards and withdrawing them.
=> docs: add cli staking queries documentation

cmd/fetchd/cmd/genaccounts.go
The `add-genesis-account` command needs a small update to work with stargate genesis,
The coins added to the accounts needs also to be added to the total supply pool
=> fix: genaccounts updates

cmd/fetchd/cmd/root.go, cmd/fetchd/cmd/stargatemigrate.go, go.mod, go.sum
This new command migrate a genesis file from current mainnet version
(sdk v0.38.3) to the stargate version (v0.42.5). Previous migration commands 
(provided by `x/genutils`) have been removed from the CLI to avoid confusion.
It handles:
- Setting default value for consensus.evidences.max_bytes which generate
a warning if 0
- Removing multisig pubkeys if present, as they fail to decode properly
with cosmos-sdk v0.38.3
- Resetting wasm module state, removing any existing contracts as they
must be recompile for the newest VM version.
- Migrate genesis from v0.38 to v0.39, and then v0.39 to v0.40
- Allow override of genesis time and chain id
=> feat: add stargate-migrate command

cmd/fetchd/cmd/gendelegations.go
Add condition to create delegations:
- when the amount exceeds the `minDelegated` amount, a delegation is created with `amount - accountReserved`, and `accountReserved` is transferred on the user account.
- otherwise, the full amount is simply transferred to the user account, and no delegation is created.
=> feat: leave some tokens on delegator accounts for txs

cmd/fetchd/cmd/stargatemigrate.go
stargate-migrate commands did not create default state for ibc
and airdrop modules, resulting in impossibility to export
the state later on.
export was failing with error: `panic: UnmarshalJSON cannot decode empty
bytes` on a `github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get` call
=> fix: missing genstate for ibc and airdrop modules

app/app.go, go.mod
* The whole code has been copyied (exactly) from Cosmos-SDK `simapp/app.go`.
=> Add support for Swagger API documentation endpoint

cmd/fetchd/cmd/root.go, go.mod, go.sum
- Updated default CLI input to be a `*bufio.Reader` in order to allow reusing the same reader when reading from multiple places.
- Pull fix from cosmos-sdk v0.17.4
=> fix: keys add --recover fail when piped from file

cmd/fetchd/cmd/root.go
it's already included via auth module
=> fix: remove duplicate tx vesting commands

config.yaml, go.mod, go.sum
Base configuration allowing to `starport chain serve` from the root of the project. 
Due to our custom SDK, I've had to fix some bits in starport itself, so you can use my branch at https://github.com/daeMOn63/starport/tree/handle_custom_sdk for now until it's merged in upstream.
Limitations:
- Only `chain serve` for now, scaffolding commands may not work as expected.
- Faucet can't work due to how starport is parsing Coin amounts that do not handle our 18 decimals token.
- There's a simple block explorer/UI usually available (from some vueJS scripts). I did leave it out for now but we can experiment with it by simply bootstrapping a dummy chain with `starport scaffold chain github.com/foo/bar` and then copying the `vue` folder to the fetchd repo root.
`config.yaml` reference available at …
=> feat: starport integration

README.md
The first paragraph had a line break between the "e" and "t" in the word "mainnet".
=> Remove line break in the middle of a word

x/group/errors.go, x/group/server/msg_server.go
when creating or updating groups and using the `--bls` flag to enforce members having bls keys, if one of the members doesn't have a bls key or haven't issued any transactions yet, the transaction currently report an obscure error like:
```
code: 1
codespace: undefined
data: ""
gas_used: "57634"
gas_wanted: "210000"
height: "2419"
info: ""
logs: []
raw_log: internal
```
This change makes it a bit easier to understand what's happening:
```
code: 210
codespace: group
data: ""
gas_used: "59306"
gas_wanted: "210000"
height: "124"
info: ""
logs: []
raw_log: 'failed to execute message; message index: 0: member fetch14s8xn6d4ku72p66n5862r2jr487xsyjxle3de8
failed bls validation: account public key not set yet: bls required'
```
=> fix: better errors when bls validation fails

scripts/devgenesis.sh
This allows updating an exported genesis (obtained from a `fetchd export...` command) with a local node keys in order to run a local chain from this genesis.
It does keep alive a single validator and jail all others in order to allow the chain to start producing blocks.
Demo:
```
fetchd export > genesis_mainnet_20220119.json
fetchd --home /tmp/localnode init localnode
./scripts/devgenesis.sh genesis_mainnet_20220119.json /tmp/localnode/
Found /tmp/localnode//config/priv_validator_key.json
- new address: 528F5CBBD654E60DDC8BD15166B52C2212510108
- new pubkey: ju1LH+L01PGNb1h1/U+0OKYIjeBRs08krtDSfGLW0R4=
- new tendermint address: fetchvalcons12284ew7k2nnqmhyt69gkddfvygf9zqgghtakdp
Replacing validator fetchvaloper1qpm07wf0y9ksd023k7lnfwzda7evcqpfsywa07...
Updating signing infos...
Updating …
```
=> feat: add devgenesis.sh script

docs/docs/networks.md
This update our network documentation with:
- Remove andromeda network details 
- Remove stargateworld network details
- Update mainnet network details from migration
- Add missing grpc endpoint to capricorn
=> docs: delete deprecated testnets

docs/docs/cli-tokens.md
* Explained that sender address must have tokens available before sending funds.
* Added link to faucet page
=> docs: add link to faucet page

.github/workflows/build_push.yml
setup-gcloud action now refuse to execute without proper version
see: https://github.com/fetchai/fetchd/runs/5659056103?check_suite_focus=true
=> fix: docker build

docs/docs/versions.md
- add missing entries for fetchd v0.9.x and v0.10.x series
- add a link to genesis-fetchhub repo for upgrade and migration docs.
=> docs: update fetchd versions doc

docs/docs/live-networks.md
Added doc for [v0.10.5-rc1](https://github.com/fetchai/fetchd/releases/tag/v0.10.5-rc1) for blocks > 2198000
=> docs: updated live-networks doc

app/genesis.go, cmd/fetchd/cmd/init.go, cmd/fetchd/cmd/root.go
This allows to generate a default genesis closer to fetch.ai default network
settings.
It's a full clone of x/genutil/client/cli/init.go, with:
- a default genesis defined with most of our network settings
- an extension of --staking-bond-denom flag, which will now set the
default denom on all other modules (gov / mint / staking / crisis)
Also align the default genesis gov vote and deposit time to 5 days, from recent mainnet change.
=> feat: custom init command

README.md, docs/docs/building.md, docs/docs/cli-introduction.md, docs/docs/faucet.md, docs/docs/index.md, docs/docs/joining-a-testnet.md, docs/docs/snapshots.md
Refreshed a bit the ledger doc landing page that was still referring to agent land network.
Fixed broken link on network page
Updated readme to remove unnecessary libc notes.
=> docs: update dead links, index & README

app/app.go, cmd/fetchd/cmd/root.go, docs/docs/state-sync.md, docs/mkdocs.yml
This removes the lock preventing to configure state-sync from fetchd, and add some docs on how to configure it.
=> feat: enable state sync

docs/docs/state-sync.md
- Replace dead endpoint from sample RPCs
- Mention increasing the default `chunk_request_timeout` timeout value
=> docs: update state sync docs

docs/docs/joining-a-testnet.md
Update curl link for dorado genesis
=> docs: Update documentation for joining a testnet

cmd/fetchd/cmd/root.go, go.mod, go.sum
Includes a new additional command `prune` within the `fetch` app
- Allows users to specify which blocks are stored locally on disk
- E.g. `fetchd prune --home './' --app-db-backend 'goleveldb' --pruning 'custom' --pruning-keep-recent 100 --
pruning-keep-every 10, --pruning-interval 10`
=> feat: Pruning - expose cli command

app/app.go, docker-compose.yml, entrypoints/run-localnet-setup.py, go.mod, go.sum
For more details see the [cosmos-sdk v0.19.0 release](https://github.com/fetchai/cosmos-sdk/releases/tag/v0.19.0), the [feat: Municipal Inflation (PR #162)](https://github.com/fetchai/cosmos-sdk/pull/162) in particular.
=> feat: Municipal Inflation

app/app.go, go.mod, go.sum
Primary feature of this upgrade is adding municipal inflation configuration for NOMX token
If NOMX token does not exists yet (as it is on Dorado testnet at the moment), or it has zero supply, then NOMX token will be created by minting `10^18 [nanonomx]` supply and denom metadata will be set - everything with the exact same values as NOMX token has on the mainnet.
=> feat: Upgrade v0.11.3: NOMX token munic. infl. & creation if required

cmd/fetchd/cmd/genasiupgrade.go
- Detects the chain ID and replaces accordingly
=> feat: testnet support

cmd/fetchd/cmd/genesis-asi-upgrade.go
- handles manual supply adjustment for ASI genesis conversion
- transfers the `additionalSupplyValue` to a hard-coded overflow address
=> feat: ASI supply replacement

cmd/fetchd/cmd/genasiupgrade.go, cmd/fetchd/cmd/genesis-asi-upgrade.go
- Complete reset of Almanac contract state
=> feat: ASI alamanac state replacement

app/app.go, app/upgrade_cudos.go, app/upgrade_cudos_distribution.go, app/upgrade_v_11_4_manifest.go, app/upgrade_v_11_4_network_config.go
=> refactor: Cudos menifest block height and community pool balance refactor

app/app.go, app/ordered_map.go, app/upgrade_cudos.go, app/upgrade_cudos_distribution.go, app/upgrade_v_11_4_manifest.go, app/upgrade_v_11_4_network_config.go
=> feat: Cudos partial balance and delegations movement

app/upgrade_cudos.go, app/upgrade_v_11_4_network_config.go
=> refactor: CUDOS nullable balance movement in config

app/upgrade_v_11_4_network_config.go
=> fix: Missing Memo field in BalanceMovements struct literals

app/app.go, app/upgrade_cudos.go, app/upgrade_cudos_distribution.go, app/upgrade_v_11_4_network_config.go, app/utils.go, cmd/fetchd/cmd/cudos_merge.go, cmd/fetchd/cmd/util.go
=> feat: Cudos config verification command

app/upgrade_cudos.go, app/upgrade_v_11_4_manifest.go, app/upgrade_v_11_4_network_config.go
=> feat: CUDOS config new validator set

app/ordered_map.go, app/upgrade_cudos.go
When you iterate over `OrderedMap.Keys()` and during iteration call `Delete` the original reference of keys gets corrupted due to in-place append in `Delete`
I've made `Delete` not to modify the original data so now it is safe to do.
=> fix: CUDOS delegations movement fix

app/upgrade_cudos.go, app/upgrade_cudos_distribution.go, app/upgrade_network_config.go
=> Refactor: CUDOS checks

app/app.go, app/ordered_map.go, app/upgrade_network_config.go, cmd/fetchd/cmd/cudos_merge.go
=> feat: CUDOS extra config verification
