entrypoints/run-node.sh

This PR adds a maintenance flag in case needed for upgrading nodes with new versions that introduce breaking changes

add-maintenance-flag

---

app/app.go
go.mod
go.sum

- Upgrade to sdk v0.7.0
- Pass bank keeper function to determine staking denomination

Update consensus and sdk versions

---

go.mod
go.sum

This updates only the consensus version

Update cosmos consensus version

---

docs/docs/validators/setup.md

Correct command for show-validator; language tweaks

docs: fixes and tweaks

---

entrypoints/run-node.sh

and an  extra check to avoid mkdir error

fix: stop on genesis overwrite failure

---

cmd/fetchd/cmd/gendelegations.go
cmd/fetchd/cmd/root.go
go.mod
go.sum

Add command allowing to introduce delegations in the genesis file.

feat: gendelegations command

---

app/app.go
go.mod
go.sum

- feat: initial airdrop module integration
- chore: update sdk reference

feat: add airdrop support

---

docs/docs/building.md
docs/docs/cli-introduction.md
docs/docs/cli-keys.md
docs/docs/cli-tokens.md
docs/docs/delegator-guide-cli.md
docs/docs/docker-images.md
docs/docs/faucet.md
docs/docs/governance.md
docs/docs/joining-a-testnet.md
docs/docs/networks.md
docs/docs/single-node-network.md
docs/docs/validators/setup.md
docs/docs/versions.md

various docs update to clarify building the app, and replaced `fetchcli` commands  with `fetchd`.
We now assume the default network is running on a stargate version
Still TODO:
> docs/docs/index.md: need to rework this one to focus more on mainnet / main testnet
> docs/docs/docker-images.md: needs to polish docker images first and agree on what we expose here first

docs: stargate updates

---

docs/docs/cli-keys.md

docs: remove AW1 section mentionning inexistent  flag

---

cmd/fetchd/cmd/capricornmigrate.go

unbonding_period config was changed from nanoseconds to seconds,
so we update the config in the contract states (both staging and prod)
to reflect this change.
- before:
```
$ jq -r '.app_state.wasm.contracts[]|select(.contract_info.code_id == "3").contract_state[]|select(.key == "636F6E666967").value' genesis_mainnet_orig.json  | base64 -d | jq
{
"owner": "fetch1m3evl6dqkhmwtp597wq8hhr9vtdasaktaq6wlj",
"chief_pausing_officer": "fetch1m9kf4s2gwpv07c6tndekxfc3vdjyup3zjggcgy",
"denom": "nanomobx",
"reward_rate": "8267196",
"paused": false,
"unbonding_period": "30000000000"
}
{
"owner": "fetch1m3evl6dqkhmwtp597wq8hhr9vtdasaktaq6wlj",
"chief_pausing_officer": "fetch1m9kf4s2gwpv07c6tndekxfc3vdjyup3zjggcgy",
"denom": "nanomobx",
"reward_rate": "8267196",
"paused": false,
"unbonding_period": …
```

feat: update mobix contract configs unbonding_period

---

docs/mkdocs.yml

Changed order of Token and Multisig pages

docs: reorder Token and Multisig pages

---

docs/docs/validators/overview.md

Thanks @ianharris-fetch for bringing this up on Discord!

docs: add new required CPU flag on hardware req.

---

docs/docs/cli-governance.md
docs/docs/cli-multisig.md
docs/docs/governance.md

* Deleted deposit flag in submit-proposal
* Explained how to get proposal ID
* Fixed  "Other multisig transaction examples"

docs: governance and multisig modifications

---

docs/docs/cli-introduction.md
docs/docs/cli-multisig.md
docs/docs/cli-tokens.md
docs/docs/delegator-guide-cli.md
docs/docs/index.md
docs/docs/joining-a-testnet.md
docs/docs/validators/setup.md

* Addressed item #3 from the Ledger docs review
* Changed all stargate mentions to capricorn

docs: change stargate for capricorn

---

docs/docs/networks.md

- update seed URLs
- include (temporary?) genesis fetch until genesis_chunked is implemented

docs: update mainnet network info

---

docs/docs/building.md
docs/docs/single-node-network.md

Added info to create a balance at genesis, and removed deleted args.

docs: updated docs to build from master

---

docs/docs/reconciliation-service.md

This PR updates the fetch wallet name in the documentation.

Update wallet name in docs

---

app/genesis.go
cmd/fetchd/cmd/init.go

Also fix the `MustWriteFile` error when running `fetchd init`

fix: align default genesis on mainnet setting

---

CODE_OF_CONDUCT.md
INTEGRATION.md
SECURITY.md

- Update security.md 
- Update code of conduct 
- typo fixes

Update md files

---

scripts/devgenesis.py

Bugfix: In the previous code we always picked the first validator, but the script failed when validator was jailed.

Jailed validator fix

---

README.md

fix: remove resource from readme

---

app/ordered_map.go
app/upgrade_v_11_4_network_config.go

fix: json decorations for Pair[...] data members & CommunityPoolBalanceDestAddr

---

app/upgrade_cudos.go
app/upgrade_cudos_distribution.go
app/upgrade_v_11_4_manifest.go
cmd/fetchd/cmd/cudos_merge.go

refactor: CUDOS Init outstanding rewards for manifest

---

app/upgrade_cudos.go
app/upgrade_cudos_distribution.go
cmd/fetchd/cmd/cudos_merge.go

feat: CUDOS Manifest utils improvements

---

cmd/fetchd/cmd/util.go

fix: Cosmetic: utils cli subcommands - add missing newlines in cli printout

---

app/upgrade_cudos.go

Fix: Cudos account movements same address fix

---

app/upgrade_cudos.go
app/upgrade_network_config.go
cmd/fetchd/cmd/cudos_merge.go

Fix: remaining module balances

---

app/upgrade_cudos.go

The only condition for validator to be configured as a "target" validator in merge config file is to be **\*NOT\*** jailed.
> Being a target validator means being capable of receiving delegations from source network during the merge.

Relaxing degree of freedom for target validator to receive delegations

---

app/upgrade_cudos.go

Fix: delegations movements
